### ISSUE TITLE
Annotation download: zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by erjel** [scalableminds/webknossos-libs#534] opened 2021-12-17 17:49 UTC
Hi,

I tested today the new [commits](https://github.com/scalableminds/webknossos-libs/commit/6d9cfaba732fac185c3e0821456f036903577516) to the webknossos python library (and a custom hack to set the largest_segment_id)
```
        with webknossos_context(url=URL, token=TOKEN):
            annotation = Annotation.download(f"{URL}/annotations/Explorational/{ID}")
            annotation_dataset = Dataset(dataset_path, scale = annotation.skeleton.scale, exist_ok=True)
            annotation.save_volume_annotation(annotation_dataset, largest_segment_id = 1)
```

unfortunately this results in the following error:
```
Traceback (most recent call last):
  File "scripts/download_annotations.py", line 37, in <module>
    annotation.save_volume_annotation(annotation_dataset, largest_segment_id = 1)
  File "${HOME}/src/webknossos-libs/webknossos/webknossos/annotation/annotation.py", line 77, in save_volume_annotation
    data_zip = ZipFile(f)
  File "${HOME}/usr/miniconda3/lib/python3.8/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "${HOME}/usr/miniconda3/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```
The code worked well on all other annotations. So I tried to download it directly via the webinterface.

- The windows zip extraction wizard also showed an error for `data.zip`
- 7zip managed to extract the file but showed the following message:
![image](https://user-images.githubusercontent.com/36883188/146586358-407172c2-7e26-484b-ab05-8b12f6669226.png)

So for me it looks like a server-site problem with the compression. As I said: This error is very strange since all my other annotations seem to work fine.

**Comment by jstriebel** [comment] 2021-12-20 09:05
Hi @erjel, thanks for reaching out. This indeed seems like an error with the webKnossos annotation. To investigate this, could you send us a link to the annotation on webknossos, e.g. via mail to hello at webknossos.org?

**Comment by erjel** [comment] 2021-12-20 10:14
mail is out

**Comment by jstriebel** [comment] 2021-12-20 11:53
Thank you, I could reproduce your problem! This indeed seems to be a problem in webknossos, probably issue https://github.com/scalableminds/webknossos/issues/5684. This helps us to investigate this further, but unfortunately I don't have a work-around yet.

**Comment by jstriebel** [comment] 2021-12-20 11:54
Closing this issue here, this will be tracked in https://github.com/scalableminds/webknossos/issues/5684

**Closed by jstriebel** 2021-12-20 11:54 UTC

**Comment by jstriebel** [comment] 2021-12-21 15:07
@erjel We investigated this further, seems to be a timeout issue, but we couldn't find the cause yet. We're going to fix this after the holidays.
