### ISSUE TITLE
Add Image.MAX_IMAGE_PIXELS = None

### ISSUE THREAD

**Issue by normanrz** [scalableminds/webknossos-libs#1153] opened 2024-07-31 18:22 UTC
I just got a `DecompressionBombError` from pims. I think we should add 
```python
from PIL import Image
Image.MAX_IMAGE_PIXELS = None
```
somewhere.

**Comment by hotzenklotz** [comment] 2024-08-01 07:34
Duplicate of #892

**Closed** 2024-08-01 16:34 UTC
